' midi-input-sequence-diagram.plantuml
' Copyright (C) 2020 Ben Tilley <targansaikhan@gmail.com>
'
' Distributed under terms of the MIT license.

@startuml

header Midi Input Sequence Diagram
title Midi Input Sequence Diagram

participant "Plugin"
participant "Audio Thread" as Audio
participant "MIDI Generator" as Generator
participant "Beat Clock" as Clock
participant "MIDI Input Trasformer" as Transformer
participant "Input Filter" as Filter
participant "Brain" as Brain
participant "MIDI Output Writer" as Writer

Plugin -> Audio : processBlock()
note over Audio : the following diagram\nassumes that the plugin is\non etc.
activate Audio
Audio -> Generator : generate_next_midi_buffer(\n  &MIDIBuffer,\n  EnvInfo,\n  &MIDIOut\n)
activate Generator

group if "Input Generation" is on
  Generator -> Clock : get_buffer_input(\n  &EnvInfo\n)
  activate Clock
  note over Clock : calculate generated input\nticks for this buffer
  return **vector<InputData>**\nGeneratedInput
end

group if "MIDI Throughput" is on
  Generator -> Transformer : get_buffer_input(\n  &MIDIBuffer\n)
  activate Transformer
  note over Transformer : calculate MIDI input\nticks for this buffer
  return **vector<InputData>**\nMIDIInput
end

group If multiple inputs
  Generator -> Generator : merge_input_streams(\n  &GeneratedInput,\n  &MIDIInput\n)
  activate Generator
  note over Generator : merge multiple input\nstreams if required
  return **vector<InputData>**\n&MergedInput
end

Generator -> Filter : filter_input(\n  &MergedInput\n)
activate Filter
note over Filter : handle merging multiple\nticks if necessary i.e.\ninput vectors only one\ntick apart
return **vector<InputData>**\n&Input

Generator -> Brain : step(&Input)
activate Brain
note over Brain : performs one step of the\nMIDI generation algorithm
return **vector<OutputData>**\n&Output

Generator -> Writer : write_midi_output(\n  &Output\n)
activate Writer
note over Writer : remembers what notes are\nplaying and sequences the\nrelevant ON/OFF MIDI\nevents
return &MIDIOut

return **&MIDIOut**

return
@enduml
